# Verbose program output
#verbose = "warn"

# Don't show interactive progress bar while checking links.
no_progress = true

# Path to summary output file.
#output = "report.md"

#############################  Cache  ###############################

# Enable link caching. This can be helpful to avoid checking the same links on
# multiple runs.
cache = true

# Discard all cached requests older than this duration.
max_cache_age = "1d"

#############################  Runtime  #############################

# Number of threads to utilize.
# Defaults to number of cores available to the system if omitted.
#threads = 2

# Maximum number of allowed redirects.
#max_redirects = 10

# Maximum number of allowed retries before a link is declared dead.
#max_retries = 2

# Maximum number of concurrent link checks.
max_concurrency = 5

#############################  Requests  ############################

# User agent to send with each request.
#user_agent = "curl/7.83. 1"

# Website timeout from connect to response finished.
#timeout = 20

# Minimum wait time in seconds between retries of failed requests.
#retry_wait_time = 2

# Comma-separated list of accepted status codes for valid links.
accept = [200, 429, 403]

# Proceed for server connections considered insecure (invalid TLS).
insecure = false

# Only test links with the given schemes (e.g. https).
# Omit to check links with any scheme.
scheme = ["https"]

# When links are available using HTTPS, treat HTTP links as errors.
require_https = true

# Request method
method = "get"

# Custom request headers
#headers = []

# Remap URI matching pattern to different URI.
#remap = [ "https://example.com http://example.invalid" ]

# Base URL or website root directory to check relative URLs.
#base = "https://example.com"

# HTTP basic auth support. This will be the username and password passed to the
# authorization HTTP header. See
# <https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Authorization>
#basic_auth = "user:pwd"

#############################  Exclusions  ##########################

# Skip missing input files (default is to error if they don't exist).
skip_missing = true

# Check links inside `<code>` and `<pre>` blocks as well as Markdown code
# blocks.
include_verbatim = true

# Ignore case of paths when matching glob patterns.
glob_ignore_case = true

# Exclude URLs and mail addresses from checking (supports regex).
exclude = [
  'domain.com',
  'opencollective.com',
  'creativecommons.org',
  'ecma-international.org',
  '2373494c71cb6d1529344a2ed1a64b03',
  'sdk/pulumi-%VERSION%',
  '/zsh-users/zsh-completions/trunk/src',
]

# Exclude these filesystem paths from getting checked.
exclude_path = [
  "i18n",
  "build",
  "node_modules",
  ".trunk/plugins",
  ".github/drafts",
]

# URLs to check (supports regex). Has preference over all excludes.
#include = [ 'gist\.github\.com.*' ]

# Exclude all private IPs from checking.
# Equivalent to setting `exclude_private`, `exclude_link_local`, and
# `exclude_loopback` to true.
exclude_all_private = true

# Exclude private IP address ranges from checking.
#exclude_private = false

# Exclude link-local IP address range from checking.
#exclude_link_local = false

# Exclude loopback IP address range and localhost from checking.
#exclude_loopback = false

# Exclude all mail addresses from checking.
exclude_mail = true
