# @format

extends:
  - stylelint-config-standard
  - stylelint-config-recommended
  - stylelint-config-recess-order
  - stylelint-config-prettier
plugins:
  - stylelint-color-format
rules:
  {
    "order/properties-alphabetical-order": null,
    "color-format/format": {"format": "hsl"},
    "selector-pseudo-class-no-unknown": [true, {ignorePseudoClasses: ["global"]}],
    "value-keyword-case": ["lower", {camelCaseSvgKeywords: true}],
    "selector-class-pattern": null,
    "custom-property-empty-line-before": null,
    "selector-id-pattern": null,
    "declaration-empty-line-before": null,
    "comment-empty-line-before": null,
  }
