extends:
  - stylelint-config-standard
  - stylelint-config-recess-order
  - stylelint-config-prettier
plugins:
  - stylelint-color-format
  - stylelint-csstree-validator
rules:
  {
    "csstree/validator": true,
    "no-descending-specificity": true,
    "declaration-block-no-duplicate-custom-properties": true,
    "declaration-block-no-duplicate-properties": true,
    "keyframe-declaration-no-important": true,
    "color-no-invalid-hex": true,
    "color-format/format": {"format": "hsl"},
    "selector-pseudo-class-no-unknown": [true, {ignorePseudoClasses: ["global"]}],
    "value-keyword-case": ["lower", {camelCaseSvgKeywords: true}],
    "block-no-empty": null,
    "order/properties-alphabetical-order": null,
    "selector-class-pattern": null,
    "custom-property-empty-line-before": null,
    "selector-id-pattern": null,
    "declaration-empty-line-before": null,
    "comment-empty-line-before": null,
  }
