---
name: 'üåê Crowdin'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'
  push:
    branches: ['main']
    paths: ['docs/**', 'community/**', 'src/**', 'blog/**', 'i18n/**']

env:
  GITHUB_TOKEN: ${{ secrets.GH_PAT }}
  CROWDIN_PROJECT: ${{ secrets.CROWDIN_PROJECT }}
  CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}

jobs:
  upload:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 10
    steps:
      - name: '‚§µÔ∏è Check out code from GitHub'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'üöÄ Crowdin Upload'
        uses: crowdin/github-action@1.4.7
        with:
          # upload_sources: true
          # upload_sources_args: '--no-auto-update label=web'
          upload_translations: true
          # auto_approve_imported: false
          # import_eq_suggestions: true
          # upload_translations_args: '--auto-approve-imported --translate-hidden'
  download:
    runs-on: ubuntu-latest
    needs: [upload]
    timeout-minutes: 30
    steps:
      - name: 'üöÄ Crowdin Download'
        uses: crowdin/github-action@1.4.7
        with:
          download_translations: true
          # skip_untranslated_strings: true
          # skip_untranslated_files: true
          # export_only_approved: true
          # download_translations_args: '--all --skip-untranslated-strings'
