---
name: 'ðŸš€ Deploy'
on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: 'ðŸš€'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    with:
      node_version: '16'
      pnpm_arguments: 'pnpm i && pnpm run build'

  upload:
    name: 'ðŸ†™'
    uses: z-shell/.github/.github/workflows/trunk.yml@main
    secrets:
      trunk-token: ${{ secrets.TRUNK_TOKEN }}
    with:
      node_version: '16'
      pnpm_arguments: 'pnpm i'
