---
name: "ğŸ”„ Rclone"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
#  schedule:
#    - cron: "0 07 * * 5"
  workflow_dispatch: {}

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
      - name: "â¤µï¸ Check out code from GitHub"
        uses: actions/checkout@v3
      - name: "â« Rclone"
        uses: z-shell/.github/actions/rclone@main
        with:
          config: ${{ secrets.R2_STORE }}
          args: sync static r2store:r2-store/public
