---
name: "üîÑ Run rclone"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  schedule:
    - cron: "0 07 * * 5"
  workflow_dispatch: {}

jobs:
  rclone:
    runs-on: ubuntu-latest
    steps:
      - name: "‚§µÔ∏è Check out code from GitHub"
        uses: actions/checkout@v3
      - name: "‚è´ Rclone"
        uses: z-shell/.github/actions/rclone@main
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_STORE }}
        with:
          args: sync static r2store:r2-store/public
