---
name: '⭕ Trunk'
on:
  push:
    branches: ['main']
    tags: ['v*.*.*']
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: 0 04 * * 1-5
  workflow_dispatch: {}

jobs:
  check-call:
    name: '⚡'
    uses: z-shell/.github/.github/workflows/trunk-call.yml@main
    #    secrets:
    #      trunk_token: ${{ secrets.TRUNK_TOKEN }}
    with:
      get_dependencies: 'sudo apt update && sudo apt install -yq zsh'
#      call_arguments1: ''
#      call_arguments2: ''
#      call_arguments3: ''
#      shell: ''
#      RUN_NODE: ''
#      RUN_NODE_VERSION: ''
#      RUN_NODE_ARGS: ''
    
      #      trunk_path: ''
      #      cache: ''
      upload-series: 'main'
      check-mode: 'all'
#      arguments: ''

