---
name: '♻️ Trunk Check'
on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: 0 04 * * 1-5

jobs:
  trunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: trunk-io/trunk-action@v1.0.1
        with:
          check-mode: all
#          trunk-token: ${{ secrets.TRUNK_TOKEN }}
